version: 1.0.{build}
image:
  #- ubuntu1604
  - ubuntu1804


environment:
  distribution: centos
  init: /usr/lib/systemd/systemd
  version: 7

services:
  - docker

install:
- 'sudo docker pull ${distribution}:${version}'

build_script:
# docker is built
- 'sudo docker build --no-cache --rm --file=tests/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible tests'
# ansible role is tested within the container
- container_id=$(mktemp)
- role_name="ansible-role-apache2"
- 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/${role_name}:ro ${distribution}-${version}:ansible ${init} > "${container_id}"'
- 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=true ansible-playbook -v /etc/ansible/roles/${role_name}/tests/test.yml --syntax-check'
- 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=true ansible-playbook -v /etc/ansible/roles/${role_name}/tests/test.yml'

# container is stopped and destroyed
- 'sudo docker stop "$(cat ${container_id})" '
- 'sudo docker rm -f "$(cat ${container_id})"'


test_script:
# test scripts must be here

build: off

# Notify Ansible Galaxy when an ansible role builds successfully.
notifications:
  - provider: Webhook
    url: https://galaxy.ansible.com/api/v1/notifications/
