version: 1.0.{build}
image: ubuntu1804

services:
  - docker

install:
#- 'sudo docker pull ${distribution}:${version}'
-  sudo docker pull centos:7
#- sudo apt-get update -qq
test_script:
#- npm test
- hostnamectl

build: off
