version: 1.0.{build}
image: ubuntu1804

environment:
  distribution: centos
  init: /usr/lib/systemd/systemd
  version: 7

services:
  - docker

install:
- 'sudo docker pull ${distribution}:${version}'
#- 'sudo docker build --no-cache --rm --file=tests/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible tests'
#-  sudo docker pull centos:7
#- sudo apt-get update -qq
build_script:
- 'sudo docker build --no-cache --rm --file=tests/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible tests'

test_script:
#- npm test


build: off
