---
# tasks file for apache
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define apache_packages.
  set_fact:
    apache_packages: "{{ apache_packages | list }}"
  when: apache_packages is not defined

# Setup/install tasks.
- include_tasks: "{{ ansible_os_family }}-install.yml"

- name: Ensure Apache has selected state and enabled on boot.
  service:
    name: "{{ apache_service }}"
    state: "{{ apache_state }}"
    enabled: true
