version: 2
jobs:
  build:
    docker:
      # Primary container image where all steps run.
     - image: buildpack-deps:bionic
     #
     - image: httpd
     #
     # - image: mongo:3.4.17-jessie
     #      command:[mongod, --smallfiles]


    working_directory: ~/

    steps:
      #- checkout
      # command will execute in trusty container
      - run:
          # testing apache
          command: curl http://localhost:8080
