version: 2
jobs:
  build:
    docker:
      # Primary container image where all steps run.
     - image: buildpack-deps:bionic
     #
     - image: httpd
     #
     - image: mongo:3.4.17-jessie

    working_directory: ~/

    steps:
      #- checkout
      # command will execute in trusty container
      - run:
          # testing apache
          # Connection refused
          #sleep 5 && nc -vz localhost 8080
          command: |
            apt-get update
            apt-get install netcat -y
            cat /etc/hosts
