version: 2
jobs:
  build:
    docker:
      # Primary container image where all steps run.
     - image: buildpack-deps:bionic
     #
     - image: httpd
     #
     - image: mongo
           command:[mongod, --smallfiles]


    working_directory: ~/

    steps:
      #- checkout
      # command will execute in trusty container
      - run:
          # testing apache
          #command: cat /etc/hosts
          command: sleep 5 && nc -vz localhost 8080
