version: 2
jobs:
  build:
    docker:
      # Primary container image where all steps run.
     - image: buildpack-deps:bionic
     #
     - image: httpd
     #
     - image: mongo:3.4.17-jessie

    working_directory: ~/

    steps:
      #- checkout
      # command will execute in trusty container
      - run:
          # testing apache
          #command: cat /etc/hosts
          command: |
            apt-get update
            apt-get install netcat -y
            sleep 5 && nc -vz localhost 8080 | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
